#!/usr/bin/env python
from netCDF4 import Dataset
import numpy
from matplotlib import use; use('Agg')
from pylab import *

#ret = numpy.zeros((10,10,12),'u1')
#for i in range(12):
#    ret[:,:,i]=i
#ret.tofile('bip_test')

#f = open('bip_test')
#for j in range(10):
#    for i in range(10):
#        print numpy.fromstring(f.read(12),dtype='u1')
#f.close()

def nc2bip(fname):
    var = fname.split('_')[0]
    ds = Dataset(fname)
    data = ds.variables[var]
    bands = len(data)
    samples, lines = data[0].shape[0], data[0].shape[1]
    suffix = '.%dx%d.bip' % (samples, lines)
    ret = numpy.zeros((samples, lines, bands), 'f4')
    for i in range(bands):
        ret[:,:,i]=data[i]
    #ret.tofile(fname.replace('.nc',suffix))
    #print(fname.replace('.nc',suffix))
    print fname
    print ret.min(), ret.max(), ret.mean()

def smap(fname):
    var = fname.split('_')[0]
    ds = Dataset(fname)
    data = ds.variables[var]
    fig = figure()
    ax = fig.add_subplot(111)
    im = imshow(data[0])
    savefig('1.png')

from glob import glob
files = glob('*.nc')
smap(files[0])
